name: facebook_auth
description: Facebook Auth Plugin for Flutter
version: 0.0.1
homepage: https://github.com/tranvansang/flutter_facebook_auth

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.transang.plugins.facebook_auth
        pluginClass: FacebookAuthPlugin
      ios:
        pluginClass: FacebookAuthPlugin
